---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## `pivot_longer`

Load the PULSE data

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Note that bdi_score measured at baseline, 1 months, 6 months, 12 months.
Instead, want to have visit variable with values (baseline, 1 mon, 6 mon, 12 mon) and bdi score for each

Wide format to long format.

```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )
```

Rewrite, combine, and extend (to add a mutate step to code chunk)
```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```

